<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SecurityHeaders
{
    /**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);

        // Only add headers to HTTP responses
        if (!$response instanceof \Illuminate\Http\Response && 
            !$response instanceof \Illuminate\Http\JsonResponse &&
            !$response instanceof \Inertia\Response) {
            return $response;
        }

        // Content Security Policy
        $csp = $this->buildContentSecurityPolicy($request);
        $response->headers->set('Content-Security-Policy', $csp);

        // HTTP Strict Transport Security (HSTS)
        if ($request->isSecure()) {
            $response->headers->set(
                'Strict-Transport-Security',
                'max-age=31536000; includeSubDomains; preload'
            );
        }

        // X-Frame-Options - Prevent clickjacking
        // Allow framing for preview mode in page builder
        if ($request->query('preview') === 'true') {
            $response->headers->set('X-Frame-Options', 'SAMEORIGIN');
        } else {
            $response->headers->set('X-Frame-Options', 'DENY');
        }

        // X-Content-Type-Options - Prevent MIME sniffing
        $response->headers->set('X-Content-Type-Options', 'nosniff');

        // X-XSS-Protection - Enable XSS filtering
        $response->headers->set('X-XSS-Protection', '1; mode=block');

        // Referrer Policy - Control referrer information
        $response->headers->set('Referrer-Policy', 'strict-origin-when-cross-origin');

        // Permissions Policy (formerly Feature Policy)
        $permissionsPolicy = $this->buildPermissionsPolicy();
        $response->headers->set('Permissions-Policy', $permissionsPolicy);

        // Cross-Origin Embedder Policy
        // Relax for local dev to avoid issues with non-HTTPS
        if (!app()->environment('local')) {
            $response->headers->set('Cross-Origin-Embedder-Policy', 'require-corp');
            $response->headers->set('Cross-Origin-Opener-Policy', 'same-origin');
            $response->headers->set('Cross-Origin-Resource-Policy', 'same-origin');
        }

        // Remove server information
        $response->headers->remove('Server');
        $response->headers->remove('X-Powered-By');

        // Cache control for sensitive pages
        if ($this->isSensitivePage($request)) {
            $response->headers->set('Cache-Control', 'no-cache, no-store, must-revalidate, private');
            $response->headers->set('Pragma', 'no-cache');
            $response->headers->set('Expires', '0');
        }

        return $response;
    }

    /**
     * Build Content Security Policy header
     */
    /**
     * Build Content Security Policy header
     */
    private function buildContentSecurityPolicy(Request $request): string
    {
        // Use the nonce generated by Vite
        $nonce = \Illuminate\Support\Facades\Vite::cspNonce();

        // If for some reason Vite didn't generate one, fall back (though Vite::useCspNonce() should handle it)
        if (!$nonce) {
            $nonce = base64_encode(random_bytes(16));
            // We'd ideally register this back with Vite, but this path shouldn't happen if AppServiceProvider is correct
        }
        
        // Store nonce for use in views (legacy support if needed directly)
        app()->instance('csp-nonce', $nonce);

        // Determine frame-ancestors based on preview mode
        $frameAncestors = $request->query('preview') === 'true' ? "'self'" : "'none'";

        $policies = [
            "default-src 'self'",
            "style-src 'self' 'unsafe-inline' https://fonts.bunny.net https://fonts.googleapis.com http://localhost:5173 http://127.0.0.1:5173",
            "font-src 'self' https://fonts.bunny.net https://fonts.gstatic.com http://localhost:5173 http://127.0.0.1:5173",
            "img-src 'self' data: https: http://localhost:5173 http://127.0.0.1:5173",
            "media-src 'self' https: http://localhost:5173 http://127.0.0.1:5173",
            "object-src 'none'",
            "base-uri 'self'",
            "form-action 'self'",
            "frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com https://player.vimeo.com https://vimeo.com",
            "frame-ancestors {$frameAncestors}",
        ];

        // Conditional CSP for Local Development vs Production
        if (app()->environment('local', 'development')) {
            // Local Dev: Relaxed rules for Vite HMR and inline scripts
            // We MUST allow 'unsafe-inline' and 'unsafe-eval' for Vite to work properly without strict-dynamic blocking it
            $policies[] = "script-src 'self' 'unsafe-inline' 'unsafe-eval' http://127.0.0.1:5173 http://localhost:5173";
            
            // Explicit script-src-elem for browsers that check this directive for <script> elements
            $policies[] = "script-src-elem 'self' 'unsafe-inline' http://127.0.0.1:5173 http://localhost:5173";
            
            // Allow Vite dev server connections
            $policies[] = "connect-src 'self' ws: wss: http://127.0.0.1:5173 ws://127.0.0.1:5173 http://localhost:5173 ws://localhost:5173";
        } else {
            // Production: Strict CSP using nonce and strict-dynamic
            $policies[] = "script-src 'self' 'nonce-{$nonce}' 'strict-dynamic'";
            
            // Standard connect-src
            $policies[] = "connect-src 'self'";
            
            // Force HTTPS
            $policies[] = "upgrade-insecure-requests";
        }

        return implode('; ', $policies);
    }

    /**
     * Build Permissions Policy header
     */
    private function buildPermissionsPolicy(): string
    {
        $policies = [
            'accelerometer=()',
            'autoplay=()',
            'camera=()',
            'cross-origin-isolated=()',
            'display-capture=()',
            'encrypted-media=()',
            'fullscreen=(self)',
            'geolocation=()',
            'gyroscope=()',
            'keyboard-map=()',
            'magnetometer=()',
            'microphone=()',
            'midi=()',
            'payment=()',
            'picture-in-picture=()',
            'publickey-credentials-get=()',
            'screen-wake-lock=()',
            'sync-xhr=()',
            'usb=()',
            'web-share=()',
            'xr-spatial-tracking=()',
        ];

        return implode(', ', $policies);
    }

    /**
     * Check if the current page is sensitive (admin, auth, etc.)
     */
    private function isSensitivePage(Request $request): bool
    {
        $sensitiveRoutes = [
            'admin/*',
            'login',
            'register',
            'password/*',
            'settings/*',
            'dashboard',
        ];

        foreach ($sensitiveRoutes as $route) {
            if ($request->is($route)) {
                return true;
            }
        }

        return false;
    }
}